#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:new_style,utf8strings
#

from evernote.thrift.Thrift import TType, TMessageType, TException, TApplicationException

from evernote.thrift.transport import TTransport
from evernote.thrift.protocol import TBinaryProtocol, TProtocol
try:
  from evernote.thrift.protocol import fastbinary
except:
  fastbinary = None


